### PR TITLE
#theCmatters

### PR DESCRIPTION
**Pull request by kentcdodds**
Adding the "C." to my name

### CODE REVIEW

**Comment by kentcdodds** [comment]
:-)

**Comment by bobbywarner** [comment]
@kentcdodds Then you need to update your photo too. See: https://github.com/midwestjs/website/commit/a9532bcfd103df78712003dfb964c1e776f6bf1c

**Comment by kentcdodds** [comment]
How could I forget! I set that up! Haha. Thanks!

**Comment by bobbywarner** [comment]
@kentcdodds New version deployed! :)

**Pull request merged**
